/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./templates/**/*.twig"],
  safelist: [
    "block",
    "text-xl",
    "border-0",
    "border-b",
    "border-black",
    "ring-0",
    "placeholder:text-grigio",
    "text-grigio",
    "focus:border-black",
    "focus:ring-0",
    "lg:text-3xl",
    "form-text",
    "w-11/12",
    "flex-column",
    "w-1/6",
    "mx-auto",
    "my-4",
    "bg-black",
    "hover:bg-grigio",
    "rounded-lg",
    "w-fit",
    "px-4",
    "py-1.5",
    "bg-black",
    "cursor-pointer",
    "hover:bg-grigio",
    "text-white",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
